### ISSUE TITLE
TTeok-spec.md 생성

### ISSUE THREAD

**Issue by seeeturtle** [ENvironmentSet/DalToki#2]
떡 언어의 명세는 변하기 쉬우므로 따로 디렉토리를 만들어 (ex. doc/) `TTeok-spec.md`를 만드는게 나을 것 같습니다.
어떻게 생각하시나요?

**Comment by seeeturtle** [comment]
버전 별로 만들면 더 나을 듯합니다

**Comment by ENvironmentSet** [comment]
좋은 생각이신 거 같습니다 바로 반영하겠습니다.

**Comment by ENvironmentSet** [comment]
아예 레포를 하나 만드는 건 어떠신가요?
