### ISSUE TITLE
Making shellscript installer for easier install

### ISSUE THREAD

**Issue by ghost** [ENvironmentSet/DalToki#4]
README.md에 있는 설치과정을 한번에 해줄 쉘스크립트 하나 만드는게 더 편할듯 합니다

**Comment by seeeturtle** [comment]
@w3bn00b, 지금 executer가 딱히 필요가 없다는 걸 알게 되서 shell script을 짤 정도로 복잡하지 않다고 생각이 듭니다.

alias로 해주면 c 코드 없이도 어디든지 실행할 수 있습니다

어떻게 생각하시나요.

**Comment by ENvironmentSet** [comment]
환경변수 등 번거로운 부분들을 설정해주는 쉘 스크립트가 장기적으로는 필요하다고는 저도 생각합니다.

**Comment by seeeturtle** [comment]
넵. 하지만 지금은 그렇게 번거롭다고 생각이 드는 과정은 없다는 생각이 드네요.
나중에 더 복잡해지면 넣으는게 맞다고 생각합니다

그리 어려운 과정은 아니니 지금 해도 상관은 없다고 봅니다

**Comment by ENvironmentSet** [comment]
그럼 쉘 스크립트 작성은 각 구현체의 재량에 맡기도록 하지요.

**Comment by seeeturtle** [comment]
넵
