### ISSUE TITLE
Problem of naming of property of object

### ISSUE THREAD

**Issue by seeeturtle** [ENvironmentSet/DalToki#5]
object type인 새로운 인스턴스를 만들 때
다른 구문들과의 통일성을 위해서 property(이름과 타입)을 담는
option을 `value`라고 지었습니다.
하지만 보통의 언어들 같은 경우에는 이러한 타입을 위해서 특별히 이름을 만드는 것이 흔하고
사용할 때 오해의 여지가 있을 수 있기 때문에
`property` 또는 `field`와 같은 이름을 사용한 것도 나쁘지 않습니다.

이는 고민을 해야 할 것입니다.

**Comment by ENvironmentSet** [comment]
init -> value 
value -> struct(구조) 로의 변경 어떠신가요.

**Comment by seeeturtle** [comment]
@ENvironmentSet, 약간 이상하지 않을 까요?
처음 볼때 `object 안에 struct가 왜 있지?` 같은 생각을 하지 않을까요?
사용자 관점에서 본다면 그럴 것 같네요.

뭐 이름은 지은이 마음이니까 그렇게 해도 상관은 없습니다

**Comment by ENvironmentSet** [comment]
그렇다면 prototype은 어떠신가요?

**Comment by ENvironmentSet** [comment]
property로 변경하였습니다.
