### ISSUE TITLE
Problem with describing english words in spec

### ISSUE THREAD

**Issue by ENvironmentSet** [ENvironmentSet/DalToki#6]
기존에는 전부 발음에 맞추어 한글로 작성했었습니다만. 직관성을 해치는 부분이 있는 거 같습니다. 영어 고유명사의 경우 영자로 표기하는 건 어떨까요?

**Comment by seeeturtle** [comment]
어떤 부분을 얘기하시는 건가요?

**Comment by ENvironmentSet** [comment]
Lexical scope나 container 같은 경우입니다
