### ISSUE TITLE
Adding %type constant for describe empty type.

### ISSUE THREAD

**Issue by ENvironmentSet** [ENvironmentSet/DalToki#9]
기존에 간단한 타입이어도, 타입을 기술하기 위해 typeof 0 (빈 숫자 타입)처럼 오버헤드를 유발하는 형식의 코드를 사용하였었습니다. 또한 직관적인 코드도 아니였습니다. 그렇기에 빈 타입을 표현하기 위한 타입 상수를 추가하는것은 어떨까요? 

%number (빈 숫자 타입), %char (빈 문자 타입), %null (null 타입), %object (빈 객체 타입), %list (빈 리스트 타입), %interface (빈 인터페이스 타입), %container (빈 컨테이너 타입) 

또한 타입 상수의 도입은 #8 의 해결책이 될 수 있다고 생각합니다.

**Comment by seeeturtle** [comment]
넵 그러는게 훨씬 직관적일 것 같습니다. 

그리고 type 상수를 지정할 수 있도록 하면 어떨까요?
그러면 새로운 타입을 만들때 편할 것 같습니다

```
<type name=%newType of=someObject />
```
이런식으로

**Comment by ENvironmentSet** [comment]
type 상수의 유효범위는 어떻게 될까요?

**Comment by ENvironmentSet** [comment]
Go의 type, C의 typedef 같은건가요?

**Comment by ENvironmentSet** [comment]
또한 명칭을 type 상수보다는 그냥 custom type define 정도가 좋을 듯 싶습니다.

**Comment by seeeturtle** [comment]
> Go의 type, C의 typedef 같은건가요?

그렇죠
> 또한 명칭을 type 상수보다는 그냥 custom type define 정도가 좋을 듯 싶습니다.

아 넵.

**Comment by ENvironmentSet** [comment]
타입 상수, 사용자 타입 정의는 추가하는걸로 하겠습니다.
